import blurData from './blur-data.generated.json';

const map = blurData as Record<string, string>;

/**
 * Blur placeholder for an image in /public. Generated by `npm run images:blur`
 * (runs automatically before every build).
 */
export function blurFor(src: string) {
  const blurDataURL = map[src];
  return blurDataURL ? ({ placeholder: 'blur', blurDataURL } as const) : ({} as const);
}
